FROM java:openjdk-8

# Install sbt
ENV SBT_VERSION 0.13.8
RUN apt-get update && \
    apt-get install -y curl && \
    curl -L http://dl.bintray.com/sbt/debian/sbt-${SBT_VERSION}.deb > /tmp/sbt-${SBT_VERSION}.deb && \
    dpkg -i /tmp/sbt-${SBT_VERSION}.deb && \
    rm /tmp/sbt-${SBT_VERSION}.deb

# Install nodejs 4.x
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get update && \
    apt-get install -y --no-install-recommends build-essential nodejs

# Install ruby
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends ruby ruby-dev bundler


# RUN apt-get install libpng-dev

EXPOSE 9000

RUN npm i -g grunt-cli

RUN mkdir -p /etc/gu/ && echo "STAGE=DEV" > /etc/gu/install_vars

VOLUME /app

WORKDIR /app
